easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Survey
       - App\Entity\Question
       - App\Entity\QuestionType
       - App\Entity\User
       - App\Entity\Blog